//	XLCTextEx_1.0x	:	XLCTextEx

//	XLCTr.h
//
#pragma once

XLOPER12* WINAPI	XLCTrCreate12(XLOPER12* pxId, XLOPER12* pxSrc, XLOPER12* pxDst, XLOPER12* pxOpt);
XLOPER* WINAPI		XLCTrCreate4(XLOPER* pxId, XLOPER* pxSrc, XLOPER* pxDst, XLOPER* pxOpt);

XLOPER12* WINAPI	XLCTrDelete12(XLOPER12* pxId);
XLOPER* WINAPI		XLCTrDelete4(XLOPER* pxId);

XLOPER12* WINAPI	XLCTr12(XLOPER12* pxArg1, XLOPER12* pxArg2, XLOPER12* pxArg3, XLOPER12* pxArg4);
XLOPER* WINAPI		XLCTr4(XLOPER* pxArg1, XLOPER* pxArg2, XLOPER* pxArg3, XLOPER* pxArg4);

XLOPER12* WINAPI	XLCToHiragana12(XLOPER12* pxStr, XLOPER12* pxOpt);
XLOPER* WINAPI		XLCToHiragana4(XLOPER* pxStr, XLOPER* pxOpt);

XLOPER12* WINAPI	XLCToKatakana12(XLOPER12* pxStr, XLOPER12* pxOpt);
XLOPER* WINAPI		XLCToKatakana4(XLOPER* pxStr, XLOPER* pxOpt);

XLOPER12* WINAPI	XLCToZenkaku12(XLOPER12* pxStr, XLOPER12* pxOpt);
XLOPER* WINAPI		XLCToZenkaku4(XLOPER* pxStr, XLOPER* pxOpt);

XLOPER12* WINAPI	XLCToZenkakuKana12(XLOPER12* pxStr, XLOPER12* pxOpt);
XLOPER* WINAPI		XLCToZenkakuKana4(XLOPER* pxStr, XLOPER* pxOpt);

XLOPER12* WINAPI	XLCToHankaku12(XLOPER12* pxStr, XLOPER12* pxOpt);
XLOPER* WINAPI		XLCToHankaku4(XLOPER* pxStr, XLOPER* pxOpt);

XLOPER12* WINAPI	XLCNormalizeWidth12(XLOPER12* pxStr, XLOPER12* pxOpt);
XLOPER* WINAPI		XLCNormalizeWidth4(XLOPER* pxStr, XLOPER* pxOpt);
