//	XLCTextEx_1.0x	:	PLibUCD

//	PLibUCD:	PBlocks.h
//
#pragma once

NS_PLIB_UNICODE_BEGIN

#define	PUCD_BLOCK_NOBLOCK	0
#define	PUCD_BLOCK_BASIC_LATIN	1
#define	PUCD_BLOCK_LATIN_1_SUPPLEMENT	2
#define	PUCD_BLOCK_LATIN_EXTENDED_A	3
#define	PUCD_BLOCK_LATIN_EXTENDED_B	4
#define	PUCD_BLOCK_IPA_EXTENSIONS	5
#define	PUCD_BLOCK_SPACING_MODIFIER_LETTERS	6
#define	PUCD_BLOCK_COMBINING_DIACRITICAL_MARKS	7
#define	PUCD_BLOCK_GREEK_AND_COPTIC	8
#define	PUCD_BLOCK_CYRILLIC	9
#define	PUCD_BLOCK_CYRILLIC_SUPPLEMENT	10
#define	PUCD_BLOCK_ARMENIAN	11
#define	PUCD_BLOCK_HEBREW	12
#define	PUCD_BLOCK_ARABIC	13
#define	PUCD_BLOCK_SYRIAC	14
#define	PUCD_BLOCK_ARABIC_SUPPLEMENT	15
#define	PUCD_BLOCK_THAANA	16
#define	PUCD_BLOCK_NKO	17
#define	PUCD_BLOCK_SAMARITAN	18
#define	PUCD_BLOCK_MANDAIC	19
#define	PUCD_BLOCK_ARABIC_EXTENDED_A	20
#define	PUCD_BLOCK_DEVANAGARI	21
#define	PUCD_BLOCK_BENGALI	22
#define	PUCD_BLOCK_GURMUKHI	23
#define	PUCD_BLOCK_GUJARATI	24
#define	PUCD_BLOCK_ORIYA	25
#define	PUCD_BLOCK_TAMIL	26
#define	PUCD_BLOCK_TELUGU	27
#define	PUCD_BLOCK_KANNADA	28
#define	PUCD_BLOCK_MALAYALAM	29
#define	PUCD_BLOCK_SINHALA	30
#define	PUCD_BLOCK_THAI	31
#define	PUCD_BLOCK_LAO	32
#define	PUCD_BLOCK_TIBETAN	33
#define	PUCD_BLOCK_MYANMAR	34
#define	PUCD_BLOCK_GEORGIAN	35
#define	PUCD_BLOCK_HANGUL_JAMO	36
#define	PUCD_BLOCK_ETHIOPIC	37
#define	PUCD_BLOCK_ETHIOPIC_SUPPLEMENT	38
#define	PUCD_BLOCK_CHEROKEE	39
#define	PUCD_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS	40
#define	PUCD_BLOCK_OGHAM	41
#define	PUCD_BLOCK_RUNIC	42
#define	PUCD_BLOCK_TAGALOG	43
#define	PUCD_BLOCK_HANUNOO	44
#define	PUCD_BLOCK_BUHID	45
#define	PUCD_BLOCK_TAGBANWA	46
#define	PUCD_BLOCK_KHMER	47
#define	PUCD_BLOCK_MONGOLIAN	48
#define	PUCD_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED	49
#define	PUCD_BLOCK_LIMBU	50
#define	PUCD_BLOCK_TAI_LE	51
#define	PUCD_BLOCK_NEW_TAI_LUE	52
#define	PUCD_BLOCK_KHMER_SYMBOLS	53
#define	PUCD_BLOCK_BUGINESE	54
#define	PUCD_BLOCK_TAI_THAM	55
#define	PUCD_BLOCK_BALINESE	56
#define	PUCD_BLOCK_SUNDANESE	57
#define	PUCD_BLOCK_BATAK	58
#define	PUCD_BLOCK_LEPCHA	59
#define	PUCD_BLOCK_OL_CHIKI	60
#define	PUCD_BLOCK_SUNDANESE_SUPPLEMENT	61
#define	PUCD_BLOCK_VEDIC_EXTENSIONS	62
#define	PUCD_BLOCK_PHONETIC_EXTENSIONS	63
#define	PUCD_BLOCK_PHONETIC_EXTENSIONS_SUPPLEMENT	64
#define	PUCD_BLOCK_COMBINING_DIACRITICAL_MARKS_SUPPLEMENT	65
#define	PUCD_BLOCK_LATIN_EXTENDED_ADDITIONAL	66
#define	PUCD_BLOCK_GREEK_EXTENDED	67
#define	PUCD_BLOCK_GENERAL_PUNCTUATION	68
#define	PUCD_BLOCK_SUPERSCRIPTS_AND_SUBSCRIPTS	69
#define	PUCD_BLOCK_CURRENCY_SYMBOLS	70
#define	PUCD_BLOCK_COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS	71
#define	PUCD_BLOCK_LETTERLIKE_SYMBOLS	72
#define	PUCD_BLOCK_NUMBER_FORMS	73
#define	PUCD_BLOCK_ARROWS	74
#define	PUCD_BLOCK_MATHEMATICAL_OPERATORS	75
#define	PUCD_BLOCK_MISCELLANEOUS_TECHNICAL	76
#define	PUCD_BLOCK_CONTROL_PICTURES	77
#define	PUCD_BLOCK_OPTICAL_CHARACTER_RECOGNITION	78
#define	PUCD_BLOCK_ENCLOSED_ALPHANUMERICS	79
#define	PUCD_BLOCK_BOX_DRAWING	80
#define	PUCD_BLOCK_BLOCK_ELEMENTS	81
#define	PUCD_BLOCK_GEOMETRIC_SHAPES	82
#define	PUCD_BLOCK_MISCELLANEOUS_SYMBOLS	83
#define	PUCD_BLOCK_DINGBATS	84
#define	PUCD_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A	85
#define	PUCD_BLOCK_SUPPLEMENTAL_ARROWS_A	86
#define	PUCD_BLOCK_BRAILLE_PATTERNS	87
#define	PUCD_BLOCK_SUPPLEMENTAL_ARROWS_B	88
#define	PUCD_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B	89
#define	PUCD_BLOCK_SUPPLEMENTAL_MATHEMATICAL_OPERATORS	90
#define	PUCD_BLOCK_MISCELLANEOUS_SYMBOLS_AND_ARROWS	91
#define	PUCD_BLOCK_GLAGOLITIC	92
#define	PUCD_BLOCK_LATIN_EXTENDED_C	93
#define	PUCD_BLOCK_COPTIC	94
#define	PUCD_BLOCK_GEORGIAN_SUPPLEMENT	95
#define	PUCD_BLOCK_TIFINAGH	96
#define	PUCD_BLOCK_ETHIOPIC_EXTENDED	97
#define	PUCD_BLOCK_CYRILLIC_EXTENDED_A	98
#define	PUCD_BLOCK_SUPPLEMENTAL_PUNCTUATION	99
#define	PUCD_BLOCK_CJK_RADICALS_SUPPLEMENT	100
#define	PUCD_BLOCK_KANGXI_RADICALS	101
#define	PUCD_BLOCK_IDEOGRAPHIC_DESCRIPTION_CHARACTERS	102
#define	PUCD_BLOCK_CJK_SYMBOLS_AND_PUNCTUATION	103
#define	PUCD_BLOCK_HIRAGANA	104
#define	PUCD_BLOCK_KATAKANA	105
#define	PUCD_BLOCK_BOPOMOFO	106
#define	PUCD_BLOCK_HANGUL_COMPATIBILITY_JAMO	107
#define	PUCD_BLOCK_KANBUN	108
#define	PUCD_BLOCK_BOPOMOFO_EXTENDED	109
#define	PUCD_BLOCK_CJK_STROKES	110
#define	PUCD_BLOCK_KATAKANA_PHONETIC_EXTENSIONS	111
#define	PUCD_BLOCK_ENCLOSED_CJK_LETTERS_AND_MONTHS	112
#define	PUCD_BLOCK_CJK_COMPATIBILITY	113
#define	PUCD_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A	114
#define	PUCD_BLOCK_YIJING_HEXAGRAM_SYMBOLS	115
#define	PUCD_BLOCK_CJK_UNIFIED_IDEOGRAPHS	116
#define	PUCD_BLOCK_YI_SYLLABLES	117
#define	PUCD_BLOCK_YI_RADICALS	118
#define	PUCD_BLOCK_LISU	119
#define	PUCD_BLOCK_VAI	120
#define	PUCD_BLOCK_CYRILLIC_EXTENDED_B	121
#define	PUCD_BLOCK_BAMUM	122
#define	PUCD_BLOCK_MODIFIER_TONE_LETTERS	123
#define	PUCD_BLOCK_LATIN_EXTENDED_D	124
#define	PUCD_BLOCK_SYLOTI_NAGRI	125
#define	PUCD_BLOCK_COMMON_INDIC_NUMBER_FORMS	126
#define	PUCD_BLOCK_PHAGS_PA	127
#define	PUCD_BLOCK_SAURASHTRA	128
#define	PUCD_BLOCK_DEVANAGARI_EXTENDED	129
#define	PUCD_BLOCK_KAYAH_LI	130
#define	PUCD_BLOCK_REJANG	131
#define	PUCD_BLOCK_HANGUL_JAMO_EXTENDED_A	132
#define	PUCD_BLOCK_JAVANESE	133
#define	PUCD_BLOCK_CHAM	134
#define	PUCD_BLOCK_MYANMAR_EXTENDED_A	135
#define	PUCD_BLOCK_TAI_VIET	136
#define	PUCD_BLOCK_MEETEI_MAYEK_EXTENSIONS	137
#define	PUCD_BLOCK_ETHIOPIC_EXTENDED_A	138
#define	PUCD_BLOCK_MEETEI_MAYEK	139
#define	PUCD_BLOCK_HANGUL_SYLLABLES	140
#define	PUCD_BLOCK_HANGUL_JAMO_EXTENDED_B	141
#define	PUCD_BLOCK_HIGH_SURROGATES	142
#define	PUCD_BLOCK_HIGH_PRIVATE_USE_SURROGATES	143
#define	PUCD_BLOCK_LOW_SURROGATES	144
#define	PUCD_BLOCK_PRIVATE_USE_AREA	145
#define	PUCD_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS	146
#define	PUCD_BLOCK_ALPHABETIC_PRESENTATION_FORMS	147
#define	PUCD_BLOCK_ARABIC_PRESENTATION_FORMS_A	148
#define	PUCD_BLOCK_VARIATION_SELECTORS	149
#define	PUCD_BLOCK_VERTICAL_FORMS	150
#define	PUCD_BLOCK_COMBINING_HALF_MARKS	151
#define	PUCD_BLOCK_CJK_COMPATIBILITY_FORMS	152
#define	PUCD_BLOCK_SMALL_FORM_VARIANTS	153
#define	PUCD_BLOCK_ARABIC_PRESENTATION_FORMS_B	154
#define	PUCD_BLOCK_HALFWIDTH_AND_FULLWIDTH_FORMS	155
#define	PUCD_BLOCK_SPECIALS	156
#define	PUCD_BLOCK_LINEAR_B_SYLLABARY	157
#define	PUCD_BLOCK_LINEAR_B_IDEOGRAMS	158
#define	PUCD_BLOCK_AEGEAN_NUMBERS	159
#define	PUCD_BLOCK_ANCIENT_GREEK_NUMBERS	160
#define	PUCD_BLOCK_ANCIENT_SYMBOLS	161
#define	PUCD_BLOCK_PHAISTOS_DISC	162
#define	PUCD_BLOCK_LYCIAN	163
#define	PUCD_BLOCK_CARIAN	164
#define	PUCD_BLOCK_OLD_ITALIC	165
#define	PUCD_BLOCK_GOTHIC	166
#define	PUCD_BLOCK_UGARITIC	167
#define	PUCD_BLOCK_OLD_PERSIAN	168
#define	PUCD_BLOCK_DESERET	169
#define	PUCD_BLOCK_SHAVIAN	170
#define	PUCD_BLOCK_OSMANYA	171
#define	PUCD_BLOCK_CYPRIOT_SYLLABARY	172
#define	PUCD_BLOCK_IMPERIAL_ARAMAIC	173
#define	PUCD_BLOCK_PHOENICIAN	174
#define	PUCD_BLOCK_LYDIAN	175
#define	PUCD_BLOCK_MEROITIC_HIEROGLYPHS	176
#define	PUCD_BLOCK_MEROITIC_CURSIVE	177
#define	PUCD_BLOCK_KHAROSHTHI	178
#define	PUCD_BLOCK_OLD_SOUTH_ARABIAN	179
#define	PUCD_BLOCK_AVESTAN	180
#define	PUCD_BLOCK_INSCRIPTIONAL_PARTHIAN	181
#define	PUCD_BLOCK_INSCRIPTIONAL_PAHLAVI	182
#define	PUCD_BLOCK_OLD_TURKIC	183
#define	PUCD_BLOCK_RUMI_NUMERAL_SYMBOLS	184
#define	PUCD_BLOCK_BRAHMI	185
#define	PUCD_BLOCK_KAITHI	186
#define	PUCD_BLOCK_SORA_SOMPENG	187
#define	PUCD_BLOCK_CHAKMA	188
#define	PUCD_BLOCK_SHARADA	189
#define	PUCD_BLOCK_TAKRI	190
#define	PUCD_BLOCK_CUNEIFORM	191
#define	PUCD_BLOCK_CUNEIFORM_NUMBERS_AND_PUNCTUATION	192
#define	PUCD_BLOCK_EGYPTIAN_HIEROGLYPHS	193
#define	PUCD_BLOCK_BAMUM_SUPPLEMENT	194
#define	PUCD_BLOCK_MIAO	195
#define	PUCD_BLOCK_KANA_SUPPLEMENT	196
#define	PUCD_BLOCK_BYZANTINE_MUSICAL_SYMBOLS	197
#define	PUCD_BLOCK_MUSICAL_SYMBOLS	198
#define	PUCD_BLOCK_ANCIENT_GREEK_MUSICAL_NOTATION	199
#define	PUCD_BLOCK_TAI_XUAN_JING_SYMBOLS	200
#define	PUCD_BLOCK_COUNTING_ROD_NUMERALS	201
#define	PUCD_BLOCK_MATHEMATICAL_ALPHANUMERIC_SYMBOLS	202
#define	PUCD_BLOCK_ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS	203
#define	PUCD_BLOCK_MAHJONG_TILES	204
#define	PUCD_BLOCK_DOMINO_TILES	205
#define	PUCD_BLOCK_PLAYING_CARDS	206
#define	PUCD_BLOCK_ENCLOSED_ALPHANUMERIC_SUPPLEMENT	207
#define	PUCD_BLOCK_ENCLOSED_IDEOGRAPHIC_SUPPLEMENT	208
#define	PUCD_BLOCK_MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS	209
#define	PUCD_BLOCK_EMOTICONS	210
#define	PUCD_BLOCK_TRANSPORT_AND_MAP_SYMBOLS	211
#define	PUCD_BLOCK_ALCHEMICAL_SYMBOLS	212
#define	PUCD_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B	213
#define	PUCD_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C	214
#define	PUCD_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D	215
#define	PUCD_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT	216
#define	PUCD_BLOCK_TAGS	217
#define	PUCD_BLOCK_VARIATION_SELECTORS_SUPPLEMENT	218
#define	PUCD_BLOCK_SUPPLEMENTARY_PRIVATE_USE_AREA_A	219
#define	PUCD_BLOCK_SUPPLEMENTARY_PRIVATE_USE_AREA_B	220

//----------------------------------------------------------------------
//	GetBlockId	ブロック名から ID を取得する。
//----------------------------------------------------------------------
bool	GetBlockIdByName(int* pid, UCPSTRING* pucsName);
bool	GetBlockIdByName(int* pid, const T_UCP* pName, size_t zName);
bool	GetBlockIdByName(int* pid, const T_UCP* pzName);

//----------------------------------------------------------------------
//	GetBlockRange	ブロック名 ID をからその範囲を取得する。
//----------------------------------------------------------------------
bool	GetBlockRange(UINT* puiCpF, UINT* puiCpL, int iBlock);

//----------------------------------------------------------------------
//	IsInBlock	指定されたブロックに属しているか調べる。
//----------------------------------------------------------------------
bool	IsInBlock(int iBlock, UINT uiCodepoint);
//bool	IsInBlock(int iBlock, const T_UCP* pChar, const T_UCP* pEnd = NULL);

/*
template<typename T_CHAR>
inline bool t_IsInBlock(int iBlock, const T_CHAR* pChar, const T_CHAR* pEnd)// = NULL)
{
	return FALSE;
}
template<>
inline bool t_IsInBlock<T_CHAR_U>(int iBlock, const T_UCP* pChar, const T_UCP* pEnd)
{
	return IsInBlock(iBlock, pChar, pEnd);
}
*/

//======================================================================
//	デバッグ用
//======================================================================
#ifdef	PDEBUG

T_PCSTR_U	Debug_GetBlockValue(int iId);

#endif

NS_PLIB_UNICODE_END
