//	XLCTextEx_1.0x	:	PLibUCD

//	PLibUCD:	PPropList.h
//
#pragma once

NS_PLIB_UNICODE_BEGIN

#define	PUCD_PROPLIST_UNDEFINED	0
#define	PUCD_PROPLIST_WHITE_SPACE	1
#define	PUCD_PROPLIST_PATTERN_WHITE_SPACE	2
#define	PUCD_PROPLIST_TERMINAL_PUNCTUATION	3
#define	PUCD_PROPLIST_STERM	4
#define	PUCD_PROPLIST_PATTERN_SYNTAX	5
#define	PUCD_PROPLIST_QUOTATION_MARK	6
#define	PUCD_PROPLIST_DASH	7
#define	PUCD_PROPLIST_HYPHEN	8
#define	PUCD_PROPLIST_HEX_DIGIT	9
#define	PUCD_PROPLIST_ASCII_HEX_DIGIT	10
#define	PUCD_PROPLIST_OTHER_MATH	11
#define	PUCD_PROPLIST_DIACRITIC	12
#define	PUCD_PROPLIST_SOFT_DOTTED	13
#define	PUCD_PROPLIST_OTHER_LOWERCASE	14
#define	PUCD_PROPLIST_EXTENDER	15
#define	PUCD_PROPLIST_OTHER_ID_CONTINUE	16
#define	PUCD_PROPLIST_DEPRECATED	17
#define	PUCD_PROPLIST_OTHER_ALPHABETIC	18
#define	PUCD_PROPLIST_OTHER_DEFAULT_IGNORABLE_CODE_POINT	19
#define	PUCD_PROPLIST_OTHER_GRAPHEME_EXTEND	20
#define	PUCD_PROPLIST_LOGICAL_ORDER_EXCEPTION	21
#define	PUCD_PROPLIST_VARIATION_SELECTOR	22
#define	PUCD_PROPLIST_JOIN_CONTROL	23
#define	PUCD_PROPLIST_BIDI_CONTROL	24
#define	PUCD_PROPLIST_OTHER_ID_START	25
#define	PUCD_PROPLIST_OTHER_UPPERCASE	26
#define	PUCD_PROPLIST_RADICAL	27
#define	PUCD_PROPLIST_IDS_BINARY_OPERATOR	28
#define	PUCD_PROPLIST_IDS_TRINARY_OPERATOR	29
#define	PUCD_PROPLIST_IDEOGRAPHIC	30
#define	PUCD_PROPLIST_UNIFIED_IDEOGRAPH	31
#define	PUCD_PROPLIST_NONCHARACTER_CODE_POINT	32

//======================================================================
//	ä÷êîÇÃêÈåæ
//======================================================================

bool	IsNoncharacterCodePoint(UINT uiCp);
//bool	IsNoncharacterCodePoint(const T_UCP* pStr, const T_UCP* pEnd);

bool	IsWhiteSpace(UINT uiCp);
//bool	IsWhiteSpace(const T_UCP* pStr, const T_UCP* pEnd);

NS_PLIB_UNICODE_END
